### ISSUE TITLE
Futuramente Migre pro Jekyll

### ISSUE THREAD

**Issue by victorperin** [degrecci/Bloguinho#2]
É um sistema de blogs que gera paginas estáticas. Eu uso ele no meu: http://victorperin.github.io
Aprenda mais sobre o jekyll: https://jekyllrb.com/

**Comment by victorperin** [comment]
Migra pro jekyll mano! :+1:

**Comment by degrecci** [comment]
Acredito que consegui, só aprender a usar, vlw :+1:

**Comment by victorperin** [comment]
:+1:
